spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: ${PORT:8080}

app:
  jwt:
    secret: ${APP_JWT_SECRET}
    expiration-minutes: ${APP_JWT_EXPIRATION_MINUTES:240}